version: '3.8'

services:
  app:
    container_name: nextjs_app
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["sh", "-c", "npm run build && npm start"]